#Create secret for mysql root password, to be accessed in Spring Boot application
#To assign values to secret keys use base64 format, and assign the result to the key
#For example: run command `echo -n 'root' | base64`

apiVersion: v1
