#UserService should start at 8081
server:
   port: 8081

spring:
  datasource:
    url:  #assign value to url defined in deployment with key MYSQL_URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:    #assign value to username defined in deployment with key MYSQL_USERNAME
    password:    #assign value to password defined in deployment with key MYSQL_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

